import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import connectDB from '@/lib/connectDB';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
connectDB()
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[820px] min-h-[953px] mx-auto bg-white border-1  overflow-hidden  shadow-2xl">
          {children}
        </div>
      </body>
    </html>
  );
}
